/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package character.sheet;

/**
 *
 * @author Reid
 */
public class charsheet extends javax.swing.JFrame {

    /**
     * Creates new form charsheet
     */
    public charsheet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tbCharacter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblRace = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPlayerName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblAlignment = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl2ndClass = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblDeity = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblHair = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblEyes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblSTRVal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblSTRModVal = new javax.swing.JLabel();
        lblDEXVal = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblDEXModVal = new javax.swing.JLabel();
        lblCONVal = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblCONModVal = new javax.swing.JLabel();
        lblINTVal = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblINTModVal = new javax.swing.JLabel();
        lblWISVal = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblWISModVal = new javax.swing.JLabel();
        lblCHAVal = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblCHAModVal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblExpLevel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblCurrentXP = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblNextLvlXP = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblGoldVal = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblSilverVal = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblCopperVal = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblTotalMoneyVal = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lblCurrHPVal = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblMaxHPVal = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        lblCarriedWeightVal = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblWeightCapacityVal = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblSpeedVal = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        lblDifficultyToHitVal = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        lblSpecialVisionVal = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        lblLanguagesVal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sbEquipment = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        sbFeats = new javax.swing.JScrollPane();
        jPanel19 = new javax.swing.JPanel();
        lblClassAbilityName = new javax.swing.JLabel();
        lblClassAbilityVal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pnlSkills = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        sbSpellbook = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        lblCharName = new javax.swing.JLabel();
        btnChangeCharacter = new javax.swing.JButton();
        btnSaveCharacter = new javax.swing.JButton();
        btnLaunchToolsWindow = new javax.swing.JButton();

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel18.setText("jLabel18");

        jLabel27.setText("Feats");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Lore"));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Characteristics"));
        jPanel1.setLayout(new java.awt.GridLayout(5, 6));

        jLabel1.setText("Race");
        jPanel1.add(jLabel1);

        lblRace.setText("Value");
        jPanel1.add(lblRace);

        jLabel8.setText("Size");
        jPanel1.add(jLabel8);

        lblSize.setText("Value");
        jPanel1.add(lblSize);

        jLabel12.setText("Player Name");
        jPanel1.add(jLabel12);

        lblPlayerName.setText("Value");
        jPanel1.add(lblPlayerName);

        jLabel2.setText("Class");
        jPanel1.add(jLabel2);

        lblClass.setText("Value");
        jPanel1.add(lblClass);

        jLabel7.setText("Age");
        jPanel1.add(jLabel7);

        lblAge.setText("Value");
        jPanel1.add(lblAge);

        jLabel13.setText("Alignment");
        jPanel1.add(jLabel13);

        lblAlignment.setText("Value");
        jPanel1.add(lblAlignment);

        jLabel3.setText("2nd Class");
        jPanel1.add(jLabel3);

        lbl2ndClass.setText("Value");
        jPanel1.add(lbl2ndClass);

        jLabel10.setText("Gender");
        jPanel1.add(jLabel10);

        lblGender.setText("Value");
        jPanel1.add(lblGender);

        jLabel23.setText("Deity");
        jPanel1.add(jLabel23);

        lblDeity.setText("Value");
        jPanel1.add(lblDeity);

        jLabel4.setText("Height");
        jPanel1.add(jLabel4);

        lblHeight.setText("Value");
        jPanel1.add(lblHeight);

        jLabel11.setText("Hair");
        jPanel1.add(jLabel11);

        lblHair.setText("Value");
        jPanel1.add(lblHair);

        jLabel9.setText("Eyes");
        jPanel1.add(jLabel9);

        lblEyes.setText("Value");
        jPanel1.add(lblEyes);

        jLabel5.setText("Weight");
        jPanel1.add(jLabel5);

        lblWeight.setText("Value");
        jPanel1.add(lblWeight);

        jPanel9.setLayout(new java.awt.GridLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ability Scores"));
        jPanel2.setLayout(new java.awt.GridLayout(6, 3));

        lblSTRVal.setText("Value");
        jPanel2.add(lblSTRVal);

        jLabel15.setText("STR");
        jPanel2.add(jLabel15);

        lblSTRModVal.setText("Value");
        jPanel2.add(lblSTRModVal);

        lblDEXVal.setText("Value");
        jPanel2.add(lblDEXVal);

        jLabel21.setText("DEX");
        jPanel2.add(jLabel21);

        lblDEXModVal.setText("Value");
        jPanel2.add(lblDEXModVal);

        lblCONVal.setText("Value");
        jPanel2.add(lblCONVal);

        jLabel19.setText("CON");
        jPanel2.add(jLabel19);

        lblCONModVal.setText("Value");
        jPanel2.add(lblCONModVal);

        lblINTVal.setText("Value");
        jPanel2.add(lblINTVal);

        jLabel25.setText("INT");
        jPanel2.add(jLabel25);

        lblINTModVal.setText("Value");
        jPanel2.add(lblINTModVal);

        lblWISVal.setText("Value");
        jPanel2.add(lblWISVal);

        jLabel28.setText("WIS");
        jPanel2.add(jLabel28);

        lblWISModVal.setText("Value");
        jPanel2.add(lblWISModVal);

        lblCHAVal.setText("Value");
        jPanel2.add(lblCHAVal);

        jLabel31.setText("CHA");
        jPanel2.add(jLabel31);

        lblCHAModVal.setText("Value");
        jPanel2.add(lblCHAModVal);

        jPanel9.add(jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Experience"));
        jPanel7.setLayout(new java.awt.GridLayout(3, 2));

        jLabel14.setText("Level");
        jPanel7.add(jLabel14);

        lblExpLevel.setText("Value");
        jPanel7.add(lblExpLevel);

        jLabel16.setText("Current XP");
        jPanel7.add(jLabel16);

        lblCurrentXP.setText("Value");
        jPanel7.add(lblCurrentXP);

        jLabel20.setText("Next Lvl XP");
        jPanel7.add(jLabel20);

        lblNextLvlXP.setText("Value");
        jPanel7.add(lblNextLvlXP);

        jPanel9.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Money"));
        jPanel8.setLayout(new java.awt.GridLayout(4, 2));

        jLabel17.setText("Gold");
        jPanel8.add(jLabel17);

        lblGoldVal.setText("Value");
        jPanel8.add(lblGoldVal);

        jLabel26.setText("Silver");
        jPanel8.add(jLabel26);

        lblSilverVal.setText("Value");
        jPanel8.add(lblSilverVal);

        jLabel30.setText("Copper");
        jPanel8.add(jLabel30);

        lblCopperVal.setText("Value");
        jPanel8.add(lblCopperVal);

        jLabel24.setText("Total");
        jPanel8.add(jLabel24);

        lblTotalMoneyVal.setText("Value");
        jPanel8.add(lblTotalMoneyVal);

        jPanel9.add(jPanel8);

        jPanel10.setLayout(new java.awt.GridLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Hit Points"));
        jPanel11.setLayout(new java.awt.GridLayout(2, 2));

        jLabel22.setText("Current HP");
        jPanel11.add(jLabel22);

        lblCurrHPVal.setText("Value");
        jPanel11.add(lblCurrHPVal);

        jLabel29.setText("Max HP");
        jPanel11.add(jLabel29);

        lblMaxHPVal.setText("Value");
        jPanel11.add(lblMaxHPVal);

        jPanel10.add(jPanel11);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Carried Weight"));
        jPanel12.setLayout(new java.awt.GridLayout(2, 2));

        jLabel34.setText("Carried Weight");
        jPanel12.add(jLabel34);

        lblCarriedWeightVal.setText("Value");
        jPanel12.add(lblCarriedWeightVal);

        jLabel33.setText("Weight Capacity");
        jPanel12.add(jLabel33);

        lblWeightCapacityVal.setText("Value");
        jPanel12.add(lblWeightCapacityVal);

        jPanel10.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Speed"));
        jPanel13.setLayout(new java.awt.GridLayout(1, 2));

        lblSpeedVal.setText("Value");
        jPanel13.add(lblSpeedVal);

        jLabel38.setText("yards/moment");
        jPanel13.add(jLabel38);

        jPanel10.add(jPanel13);

        jPanel15.setLayout(new java.awt.GridLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Difficulty to Hit"));
        jPanel16.setLayout(new java.awt.GridLayout(1, 1));

        lblDifficultyToHitVal.setText("Value");
        jPanel16.add(lblDifficultyToHitVal);

        jPanel15.add(jPanel16);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Special Vision"));
        jPanel17.setLayout(new java.awt.GridLayout(1, 1));

        lblSpecialVisionVal.setText("Value");
        jPanel17.add(lblSpecialVisionVal);

        jPanel15.add(jPanel17);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Languages"));
        jPanel18.setLayout(new java.awt.GridLayout());

        lblLanguagesVal.setText("Value");
        jPanel18.add(lblLanguagesVal);

        jPanel15.add(jPanel18);

        javax.swing.GroupLayout tbCharacterLayout = new javax.swing.GroupLayout(tbCharacter);
        tbCharacter.setLayout(tbCharacterLayout);
        tbCharacterLayout.setHorizontalGroup(
            tbCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbCharacterLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbCharacterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tbCharacterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tbCharacterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tbCharacterLayout.setVerticalGroup(
            tbCharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbCharacterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Character", tbCharacter);
        tbCharacter.getAccessibleContext().setAccessibleName("tbCharacter");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sbEquipment, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sbEquipment, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Equipment", jPanel3);

        sbFeats.setBorder(javax.swing.BorderFactory.createTitledBorder("Feats"));

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Class Ability"));
        jPanel19.setLayout(new java.awt.GridLayout(1, 2));

        lblClassAbilityName.setText("Ability Name");
        jPanel19.add(lblClassAbilityName);

        lblClassAbilityVal.setText("Value");
        jPanel19.add(lblClassAbilityVal);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 394, Short.MAX_VALUE))
                    .addComponent(sbFeats))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sbFeats, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        jTabbedPane1.addTab("Feats", jPanel4);

        pnlSkills.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSkills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSkills, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Skills", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sbSpellbook, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sbSpellbook, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Spellbook", jPanel6);

        jLabel6.setText("Character Name:");

        lblCharName.setText("Value");

        btnChangeCharacter.setText("Change Character");
        btnChangeCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeCharacterActionPerformed(evt);
            }
        });

        btnSaveCharacter.setText("Save Character");
        btnSaveCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCharacterActionPerformed(evt);
            }
        });

        btnLaunchToolsWindow.setText("Launch Tools Window");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblCharName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveCharacter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChangeCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLaunchToolsWindow)
                .addGap(225, 225, 225))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChangeCharacter, btnSaveCharacter});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnChangeCharacter)
                        .addComponent(btnSaveCharacter))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lblCharName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLaunchToolsWindow)
                .addGap(5, 5, 5))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tbCharacter");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnChangeCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeCharacterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeCharacterActionPerformed

    private void btnSaveCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCharacterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveCharacterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(charsheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(charsheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(charsheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(charsheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new charsheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeCharacter;
    private javax.swing.JButton btnLaunchToolsWindow;
    private javax.swing.JButton btnSaveCharacter;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl2ndClass;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAlignment;
    private javax.swing.JLabel lblCHAModVal;
    private javax.swing.JLabel lblCHAVal;
    private javax.swing.JLabel lblCONModVal;
    private javax.swing.JLabel lblCONVal;
    private javax.swing.JLabel lblCarriedWeightVal;
    private javax.swing.JLabel lblCharName;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblClassAbilityName;
    private javax.swing.JLabel lblClassAbilityVal;
    private javax.swing.JLabel lblCopperVal;
    private javax.swing.JLabel lblCurrHPVal;
    private javax.swing.JLabel lblCurrentXP;
    private javax.swing.JLabel lblDEXModVal;
    private javax.swing.JLabel lblDEXVal;
    private javax.swing.JLabel lblDeity;
    private javax.swing.JLabel lblDifficultyToHitVal;
    private javax.swing.JLabel lblExpLevel;
    private javax.swing.JLabel lblEyes;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGoldVal;
    private javax.swing.JLabel lblHair;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblINTModVal;
    private javax.swing.JLabel lblINTVal;
    private javax.swing.JLabel lblLanguagesVal;
    private javax.swing.JLabel lblMaxHPVal;
    private javax.swing.JLabel lblNextLvlXP;
    private javax.swing.JLabel lblPlayerName;
    private javax.swing.JLabel lblRace;
    private javax.swing.JLabel lblSTRModVal;
    private javax.swing.JLabel lblSTRVal;
    private javax.swing.JLabel lblSilverVal;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSpecialVisionVal;
    private javax.swing.JLabel lblSpeedVal;
    private javax.swing.JLabel lblTotalMoneyVal;
    private javax.swing.JLabel lblWISModVal;
    private javax.swing.JLabel lblWISVal;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWeightCapacityVal;
    private javax.swing.JPanel pnlSkills;
    private javax.swing.JScrollPane sbEquipment;
    private javax.swing.JScrollPane sbFeats;
    private javax.swing.JScrollPane sbSpellbook;
    private javax.swing.JPanel tbCharacter;
    // End of variables declaration//GEN-END:variables
}
